import type { TemplateCatalog } from "./types";

const defaultCopyPolicy = {
    include: [
        "projects/<source-slug>/",
        "src/compositions/<source-slug>/",
        "public/ranking-corridor/<source-slug>/",
    ],
    exclude: [
        "projects/<source-slug>/review-artifacts/",
        "projects/<source-slug>/exports/",
    ],
} as const;

const defaultReplacementPolicy = {
    replaceSourceSlug: true,
    replaceCompositionImports: true,
    replacePublicAssetPaths: true,
    replaceProjectPathReferences: true,
    replaceCompositionId: true,
} as const;

export const TEMPLATE_CATALOG = [
    {
        id: "classic-tower-template-v1",
        label: "Classic Tower Corridor",
        description: "Башенная база для классических corridor-рейтингов.",
        sourceProjectSlug: "ranking-towers",
        sourceKind: "composition-only",
        projectContainerPath: null,
        compositionPath: "src/compositions/ranking-towers",
        publicAssetsPath: null,
        compositionIdTemplate: "{{projectSlugPascal}}Corridor",
        rootRegistrationTarget: "src/Root.tsx",
        cameraPackageId: "camera-soft-side-orbit-classic-v1",
        heroPackageId: "hero-tower-hologram-monolith-v1",
        sceneWorldBaseline: ["corridor-relief-ground-v1", "horizon-mountain-ridge-v1", "low-poly-cloud-v1"],
        requiredDataShape: ["rank", "title", "value", "imageSrc?"],
        allowedAdaptationScope: "theme-tuning",
        fallbackRule: "Если тема не держится на башенной family, предложить media-stele или template-fork-required.",
        copyPolicy: defaultCopyPolicy,
        placeholderReplacementPolicy: defaultReplacementPolicy,
    },
    {
        id: "media-stele-corridor-template-v1",
        label: "Media Stele Corridor",
        description: "База под image-first corridor на стелах, близкая к сайтам и медийным темам.",
        sourceProjectSlug: "2026-03-20-most-visited-websites",
        sourceKind: "project-container",
        projectContainerPath: "projects/2026-03-20-most-visited-websites",
        compositionPath: "src/compositions/most-visited-websites",
        publicAssetsPath: null,
        compositionIdTemplate: "{{projectSlugPascal}}Corridor",
        rootRegistrationTarget: "src/Root.tsx",
        cameraPackageId: "camera-rail-focus-vip-finale-v1",
        heroPackageId: "hero-media-stele-shell-v1",
        sceneWorldBaseline: ["highway-ribbon-v1", "corridor-relief-ground-v1", "storm-effects-v1"],
        requiredDataShape: ["rank", "name", "metric", "logoSrc", "country?"],
        allowedAdaptationScope: "data-only",
        fallbackRule: "Если нужен другой hero family, оставить template-clone и предложить ближайший hero package без переписывания camera baseline.",
        copyPolicy: defaultCopyPolicy,
        placeholderReplacementPolicy: defaultReplacementPolicy,
    },
    {
        id: "nature-altar-corridor-template-v1",
        label: "Nature Altar Corridor",
        description: "Природно-монументальная база со stele/altar характером, близкая к покемонам.",
        sourceProjectSlug: "2026-03-25-strongest-pokemon",
        sourceKind: "project-container",
        projectContainerPath: "projects/2026-03-25-strongest-pokemon",
        compositionPath: "src/compositions/2026-03-25-strongest-pokemon",
        publicAssetsPath: "public/ranking-corridor/2026-03-25-strongest-pokemon",
        compositionIdTemplate: "{{projectSlugPascal}}Corridor",
        rootRegistrationTarget: "src/Root.tsx",
        cameraPackageId: "camera-rail-focus-vip-finale-v1",
        heroPackageId: "hero-stone-altar-pedestal-v1",
        sceneWorldBaseline: [
            "horizon-mountain-ridge-v1",
            "forest-backdrop-v1",
            "steam-train-line-v1",
            "low-poly-cloud-v1",
            "storm-effects-v1",
            "corridor-relief-ground-v1",
        ],
        requiredDataShape: ["rank", "name", "metric", "imageSrc", "country?"],
        allowedAdaptationScope: "scene-world-tuning",
        fallbackRule: "Если тема не выдерживает природный world baseline, предложить другой template вместо скрытого greenfield.",
        copyPolicy: defaultCopyPolicy,
        placeholderReplacementPolicy: defaultReplacementPolicy,
    },
    {
        id: "portrait-biography-corridor-template-v1",
        label: "Portrait Biography Corridor",
        description: "База под персональные биографии и portrait-heavy corridor-ролики.",
        sourceProjectSlug: "2026-03-30-richest-women",
        sourceKind: "project-container",
        projectContainerPath: "projects/2026-03-30-richest-women",
        compositionPath: "src/compositions/2026-03-30-richest-women",
        publicAssetsPath: "public/ranking-corridor/2026-03-30-richest-women",
        compositionIdTemplate: "{{projectSlugPascal}}Corridor",
        rootRegistrationTarget: "src/Root.tsx",
        cameraPackageId: "camera-biography-stele-focus-hold-v1",
        heroPackageId: "hero-portrait-biography-stele-v1",
        sceneWorldBaseline: ["horizon-mountain-ridge-v1", "birch-backdrop-v1", "low-poly-cloud-v1", "corridor-relief-ground-v1"],
        requiredDataShape: ["order", "name", "photoSrc", "country", "wealth", "fact"],
        allowedAdaptationScope: "theme-tuning",
        fallbackRule: "Если нужна radical смена hero grammar или camera family, переводить запрос в template-fork-required.",
        copyPolicy: defaultCopyPolicy,
        placeholderReplacementPolicy: defaultReplacementPolicy,
    },
] as const satisfies TemplateCatalog;
